sudo: required

services:
    - docker

before_install:
    - docker build -t lidongdong559/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lidongdong559/docker-react npm run test -- --coverage