sudo: required

services:
    - docker

before_install:
    - docker build -t lidongdong559/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lidongdong559/docker-react npm run test -- --coverage

# deploy:
#     edge: true
#     provider: elasticbeanstalk
#     region: "us-east-2"
#     app: "docker-react"
#     env: "DockerReact-env-1"
#     bucket_name: "elasticbeanstalk-us-east-2-412644925561"
#     bucket_path: "docker-react"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY

deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-west-2"
    app: "docker-react"
    env: "docker-react-env"
    bucket_name: "elasticbeanstalk-us-west-2-412644925561"